[tool.poetry]
name = "oterm"
version = "0.1.4"
description = "A text-based terminal client for Ollama."
authors = ["Yiorgis Gozadinos <ggozadinos@gmail.com>"]
homepage = "https://github.com/ggozad/oterm"
repository = "https://github.com/ggozad/oterm"
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]

[tool.poetry.scripts]
oterm = "oterm.cli.oterm:cli"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/ggozad/oterm/issues"

[tool.poetry.dependencies]
python = "^3.10"
textual = "^0.40.0"
typer = "^0.9.0"
python-dotenv = "^1.0.0"
httpx = "^0.25.0"
aiosql = "^9.0"
aiosqlite = "^0.19.0"
pyperclip = "^1.8.2"

[tool.poetry.group.dev.dependencies]
pdbpp = "^0.10.3"
ruff = "^0.1.0"
black = "^23.9.1"
pytest = "^7.4.2"
pytest-asyncio = "^0.21.1"
textual-dev = "^1.2.1"

[tool.black]
line-length = 88
target-versions = ["py310"]

[tool.ruff]
line-length = 88
# Enable Flake's "E" and "F" codes by default and "I" for sorting imports.
select = ["E", "F", "I"]
ignore = ["E501", "E741"] # E741 should not be ignored
# Exclude a variety of commonly ignored directories.
exclude = [
    ".direnv",
    ".eggs",
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    ".cache",
    "_build",
    "build",
    "dist",
    "venv",
]
per-file-ignores = { "__init__.py" = ["F401", "F403"] }
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# Assume Python 3.10.
target-version = "py310"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
